/* The Still Becoming Village Circle — persistent soundtrack + shared navigation */
(function(){
'use strict';
if(window.__TSBVC_MUSIC__)return;window.__TSBVC_MUSIC__=true;
const PLAYER_ID='villageSoundtrack';
const NAV_PAGES=new Set(['index.html','about.html','LearningtheUnknown.html','experiences.html','events.html','contact.html','coaching.html','kitta.html']);
const CANONICAL_PAGES={'events.html':'experiences.html'};
const BOOKING_URL='https://calendly.com/thestillbecomingvillagecircle/30min';
const COVER='/bricks-cover.jpeg';
const MUSIC_SRC='https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/soundcloud%253Atracks%253A1935974870&color=%2316aaa9&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=false';
let widget=null,ready=false,playing=false,playRequested=true;
function removeLegacy(){document.querySelectorAll('#soundtrack,.soundtrack,#musicBubble,.music-bubble').forEach(e=>e.remove())}
function styles(){if(document.getElementById('village-music-styles'))return;const s=document.createElement('style');s.id='village-music-styles';s.textContent=`
#${PLAYER_ID}{position:fixed;right:18px;bottom:18px;width:112px;height:112px;z-index:99999;background:transparent;border:0;box-shadow:none;display:flex;align-items:center;justify-content:center;cursor:pointer}
#${PLAYER_ID} .closed{position:relative;width:112px;height:112px;display:flex;align-items:center;justify-content:center;background:transparent;border:0}
#${PLAYER_ID} .music-orb{width:110px;height:110px;display:flex;align-items:center;justify-content:center;background:transparent}
#${PLAYER_ID} .sax{position:relative;width:110px;height:110px;display:flex;align-items:center;justify-content:center;filter:drop-shadow(0 6px 10px rgba(40,120,120,.10))}
.sax-bubble{width:110px;height:110px;display:block;overflow:visible}
.sax-bubble .cover{opacity:.54}
.sax-bubble .glass{fill:rgba(218,255,251,.18);stroke:rgba(255,255,255,.94);stroke-width:1.5}
.sax-bubble .tube{fill:none;stroke:rgba(255,255,255,.88);stroke-width:2.1;stroke-linecap:round;stroke-linejoin:round}
.sax-bubble .shine{fill:none;stroke:rgba(255,255,255,.92);stroke-width:1.8;stroke-linecap:round}
.sax-bubble .key{fill:rgba(255,255,255,.58);stroke:rgba(70,140,140,.18);stroke-width:1}
.sax-bubble .bubble-highlight{fill:rgba(255,255,255,.20);stroke:rgba(255,255,255,.70);stroke-width:1}
#${PLAYER_ID} .play{position:absolute;left:62%;top:72%;transform:translate(-50%,-50%);width:25px;height:25px;border:1px solid rgba(255,255,255,.78);border-radius:50%;background:rgba(220,255,251,.22);color:rgba(255,255,255,.95);display:flex;align-items:center;justify-content:center;font:12px Arial,sans-serif;box-shadow:none;text-shadow:0 1px 3px rgba(40,120,120,.25)}
#${PLAYER_ID}.playing .play{font-size:0}#${PLAYER_ID}.playing .play:after{content:'❚❚';font-size:9px;letter-spacing:-1px}
#${PLAYER_ID} .content{position:absolute;left:-9999px;top:-9999px;width:1px;height:1px;opacity:0;pointer-events:none;overflow:hidden}
#${PLAYER_ID}.open .content{position:fixed;right:20px;bottom:20px;left:auto;top:auto;width:min(390px,calc(100vw - 40px));height:auto;opacity:1;pointer-events:auto;overflow:visible;background:rgba(235,255,252,.94);border:1px solid rgba(255,255,255,.85);border-radius:24px;padding:16px;box-shadow:0 18px 45px rgba(40,120,120,.18);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px)}
#${PLAYER_ID} .cover-open{display:block;width:150px;height:150px;object-fit:cover;border-radius:18px;margin:0 auto 10px;box-shadow:0 10px 24px rgba(40,120,120,.14)}
#${PLAYER_ID} .title{text-align:center;color:#285f61;font:700 17px Arial,sans-serif;margin-bottom:2px}#${PLAYER_ID} .song{text-align:center;color:#16aaa9;font:14px Arial,sans-serif;margin-bottom:10px}
#${PLAYER_ID} iframe{width:100%;height:166px;border:0;border-radius:16px;overflow:hidden}#${PLAYER_ID} .close{display:block;margin:9px auto 0;border:0;background:rgba(255,255,255,.9);color:#285f61;padding:7px 20px;border-radius:25px;font-weight:700;cursor:pointer}
@media(max-width:600px){#${PLAYER_ID}{width:94px;height:94px;right:5px;bottom:8px}#${PLAYER_ID} .closed{width:94px;height:94px}#${PLAYER_ID} .music-orb,#${PLAYER_ID} .sax,.sax-bubble{width:92px;height:92px}#${PLAYER_ID} .play{width:23px;height:23px}}
.conversation-link,.becoming-journey-link{margin-top:10px!important;padding:13px 24px;border:0;border-radius:52% 48% 45% 55% / 48% 55% 45% 52%;background:rgba(22,170,169,.10);color:#16aaa9;font-family:inherit;font-size:inherit;font-weight:700;line-height:1.4;cursor:pointer;box-shadow:0 10px 24px rgba(40,120,120,.08)}
`;document.head.appendChild(s)}
function state(v){playing=!!v;const p=document.getElementById(PLAYER_ID);if(p)p.classList.toggle('playing',playing)}
function play(){if(!widget||!ready)return false;try{widget.play();return true}catch(e){return false}}
function requestPlay(){playRequested=true;if(ready)play()}
function pause(){if(widget&&ready)try{widget.pause()}catch(e){}}
function setup(){const f=document.querySelector(`#${PLAYER_ID} .soundcloud-frame`);if(!f||f.dataset.bound==='1')return;function bind(){if(!window.SC||!window.SC.Widget)return;widget=window.SC.Widget(f);widget.bind(window.SC.Widget.Events.READY,function(){ready=true;f.dataset.bound='1';widget.bind(window.SC.Widget.Events.PLAY,()=>state(true));widget.bind(window.SC.Widget.Events.PAUSE,()=>state(false));widget.bind(window.SC.Widget.Events.FINISH,function(){try{widget.seekTo(0);widget.play()}catch(e){}});if(playRequested)play()})}if(window.SC&&window.SC.Widget)bind();else{let a=document.getElementById('soundcloud-widget-api');if(!a){a=document.createElement('script');a.id='soundcloud-widget-api';a.src='https://w.soundcloud.com/player/api.js';a.onload=bind;document.head.appendChild(a)}else a.addEventListener('load',bind,{once:true})}}
function gesture(){if(window.__TSBVC_SCROLL_MUSIC__)return;window.__TSBVC_SCROLL_MUSIC__=true;let done=false;function go(){if(done)return;done=true;requestPlay();['touchstart','touchend','pointerdown','pointerup','click','wheel','touchmove','pointermove','scroll'].forEach(t=>window.removeEventListener(t,go))}['touchstart','touchend','pointerdown','pointerup','click','wheel','touchmove','pointermove','scroll'].forEach(t=>window.addEventListener(t,go,{passive:true}))}
function player(){if(document.getElementById(PLAYER_ID))return;const e=document.createElement('div');e.id=PLAYER_ID;e.innerHTML=`<div class="closed" aria-label="The Village Soundtrack"><div class="music-orb"><span class="sax" aria-hidden="true"><svg class="sax-bubble" viewBox="0 0 120 120"><defs><clipPath id="saxClip"><path d="M77 10 C67 12 61 18 61 27 C61 34 66 38 68 44 L72 67 C74 79 68 91 58 99 C49 106 35 108 24 103 C16 99 12 92 15 85 C18 78 25 75 33 77 L43 80 C49 82 53 78 52 72 L47 40 C45 29 48 18 57 11 C63 6 71 5 77 10 Z"/></clipPath><linearGradient id="glassFill" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#fff" stop-opacity=".48"/><stop offset=".55" stop-color="#d8fffb" stop-opacity=".18"/><stop offset="1" stop-color="#9ee7e0" stop-opacity=".06"/></linearGradient></defs><image class="cover" href="${COVER}" x="0" y="0" width="120" height="120" preserveAspectRatio="xMidYMid slice" clip-path="url(#saxClip)"/><path class="glass" d="M77 10 C67 12 61 18 61 27 C61 34 66 38 68 44 L72 67 C74 79 68 91 58 99 C49 106 35 108 24 103 C16 99 12 92 15 85 C18 78 25 75 33 77 L43 80 C49 82 53 78 52 72 L47 40 C45 29 48 18 57 11 C63 6 71 5 77 10 Z" fill="url(#glassFill)"/><path class="tube" d="M77 10 C85 9 93 13 98 19 C102 24 101 29 97 31 C93 33 89 30 89 26 C89 22 86 20 81 21"/><path class="tube" d="M93 19 L104 15 L108 18 L98 23"/><path class="tube" d="M58 38 L49 42 M60 49 L51 53 M62 60 L53 64"/><circle class="key" cx="55" cy="38" r="3"/><circle class="key" cx="57" cy="49" r="3"/><circle class="key" cx="59" cy="60" r="3"/><path class="shine" d="M26 80 C20 82 18 87 20 91"/><path class="shine" d="M58 16 C52 21 51 28 53 34"/><circle class="bubble-highlight" cx="103" cy="31" r="6"/><circle class="bubble-highlight" cx="110" cy="42" r="3"/></svg></span><div class="play" aria-hidden="true">▶</div></div></div><div class="content" onclick="event.stopPropagation()"><img class="cover-open" src="${COVER}" alt="Bricks — Andra Day cover art"><div class="title">The Village Soundtrack</div><div class="song">Bricks — Andra Day</div><iframe class="soundcloud-frame" scrolling="no" frameborder="no" allow="autoplay; encrypted-media" title="The Village Soundtrack" src="${MUSIC_SRC}"></iframe><button class="close" type="button">Close</button></div>`;document.body.appendChild(e);e.querySelector('.closed').addEventListener('click',()=>playing?pause():requestPlay());e.querySelector('.close').addEventListener('click',()=>e.classList.remove('open'));setup();gesture()}
function floating(root){const b=root.querySelector?.('#floatingBubble')||document.getElementById('floatingBubble'),m=root.querySelector?.('#floatingMessage')||document.getElementById('floatingMessage');if(!b||!m||b.dataset.villageBubbleInitialized==='true')return;b.dataset.villageBubbleInitialized='true';const msgs=['🫧 You belong before you bloom.',"🫧 Healing isn't linear.",'🫧 Rest is productive.','🫧 Curiosity creates connection.','🫧 Becoming takes courage.',"🫧 It's okay to begin again.",'🫧 You are allowed to change.',"🫧 You don't have to rush becoming."];let i=0,x=12,y=62,tx=12,ty=62;function pos(){const mx=innerWidth<600?68:78,my=innerWidth<600?78:84;tx=8+Math.random()*(mx-8);ty=14+Math.random()*(my-14)}function anim(){if(!document.body.contains(b))return;x+=(tx-x)*.0028;y+=(ty-y)*.0028;b.style.left=x+'%';b.style.top=y+'%';requestAnimationFrame(anim)}function change(){if(!document.body.contains(b))return;b.classList.remove('visible');setTimeout(()=>{if(!document.body.contains(b))return;i=(i+1)%msgs.length;m.textContent=msgs[i];pos();b.classList.add('visible')},1800)}pos();setTimeout(()=>b.classList.add('visible'),1200);setInterval(change,9000);anim()}
function normalize(){document.querySelectorAll('a[href]').forEach(l=>{const raw=l.getAttribute('href');if(!raw||raw.startsWith('#')||raw.startsWith('mailto:')||raw.startsWith('tel:'))return;try{const u=new URL(raw,location.href);if(u.origin!==location.origin)return;const p=u.pathname.split('/').pop()||'index.html';if(CANONICAL_PAGES[p]){u.pathname=u.pathname.replace(p,CANONICAL_PAGES[p]);l.href=u.href}}catch(e){}});document.querySelectorAll('a[href*="calendly.com"]').forEach(l=>{l.href=BOOKING_URL;l.target='_blank';l.rel='noopener noreferrer'})}
function clean(root){const reps=[[/honest conversations/gi,'honest reflection'],[/creative conversations/gi,'creative exploration'],[/the conversation to begin/gi,'the connection to begin'],[/start the conversation here/gi,'start here'],[/A conversation\./g,'An exploration.'],[/conversations/gi,'exploration'],[/conversation/gi,'exploration']];const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),a=[];let n;while(n=w.nextNode())a.push(n);a.forEach(t=>{if(!t.nodeValue.trim())return;let v=t.nodeValue;reps.forEach(r=>v=v.replace(r[0],r[1]));t.nodeValue=v})}
function fixes(){normalize();clean(document.body);const j=document.querySelector('.conversation-link'),f=document.getElementById('conversation');if(j&&f){j.textContent='🌱 Let’s Take a Journey Into Your Becoming  →';j.classList.remove('conversation-link');j.classList.add('becoming-journey-link');j.onclick=e=>{e.preventDefault();f.scrollIntoView({behavior:'smooth',block:'start'})}}const fs=document.getElementById('conversation');if(fs)fs.id='journey';const w=document.querySelector('.word-box h2');if(w&&/Epistemic Humility/i.test(w.textContent)){w.textContent='Liminality';const d=document.querySelector('.word-definition');if(d)d.textContent='noun — the state of being between one stage, condition, identity, or place and another'}}
async function nav(url,push){const u=new URL(url,location.href);let p=u.pathname.split('/').pop()||'index.html';if(CANONICAL_PAGES[p]){p=CANONICAL_PAGES[p];u.pathname=u.pathname.replace(u.pathname.split('/').pop(),p)}if(u.origin!==location.origin||!NAV_PAGES.has(p))return false;const r=await fetch(u.href,{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw Error(r.status);const parsed=new DOMParser().parseFromString(await r.text(),'text/html');const player=document.getElementById(PLAYER_ID);if(!player)return false;document.title=parsed.title||document.title;parsed.head.querySelectorAll('style').forEach(s=>document.head.appendChild(document.importNode(s,true)));[...document.body.children].forEach(c=>{if(c!==player)c.remove()});[...parsed.body.children].filter(c=>c.id!==PLAYER_ID&&!c.classList.contains('soundtrack')&&!c.classList.contains('music-bubble')).forEach(c=>document.body.insertBefore(document.importNode(c,true),player));fixes();floating(document);if(push)history.pushState({village:true},'',u.href);scrollTo({top:0,behavior:'instant'});return true}
document.addEventListener('click',e=>{const l=e.target.closest?.('a[href]');if(!l||l.target==='_blank'||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;const u=new URL(l.href,location.href),p=u.pathname.split('/').pop()||'index.html';if(u.origin!==location.origin||!NAV_PAGES.has(p)||u.pathname===location.pathname)return;e.preventDefault();nav(u.href,true).catch(()=>location.href=u.href)});
window.addEventListener('popstate',()=>nav(location.href,false).catch(()=>{}));
function init(){removeLegacy();styles();player();playRequested=true;requestPlay();fixes();floating(document)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();