name: Restore index

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  restore:
    if: ${{ !contains(github.event.head_commit.message, 'Restore index to stable version') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore stable index
        run: git checkout 6caf3fbb5c8cad3c30969f1dafff3690ac34acdb -- index.html
      - name: Commit restore
        run: |
          git config user.name "TheStillBecomingVillageCircle"
          git config user.email "waterwinewednesday@gmail.com"
          git add index.html
          git commit -m "Restore index to stable version"
          git push
